name: deploy lambdas

on: 
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Debug repository structure
        run: |
          pwd
          ls -la
          ls -la ..
          find .. -name requirements.txt

      - name: Install Lambda dependencies
        run: |
          mkdir -p ../package
          pip install -r ../lambdas/requirements.txt -t ../package

      - name: Copy Lambda source
        run: |
          cp -r ../lambdas/* ../package/

      - name: Create Lambda ZIP
        run: |
          cd ../package
          zip -r ../lambdas.zip .

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
